### ISSUE TITLE
Optimization suggestions for search

### ISSUE THREAD

**Issue by amoeet** [Nuked88/ComfyUI-N-Sidebar#10]
I hope the search can ignore case and support reverse order, for example, searching for "load image" includes:“
"IMAGE load XXXX"

**Comment by Nuked88** [comment]
The search is already ignoring case, for the reverse order is not a really easy thing to do, but i'll try my best

**Comment by clayne** [comment]
They're basically asking for a tokenized search where you split the input string based on whitespace and/or non-"word" characters, perform the search for each token, then merge the results.

Note: this could be annoying in some cases where a user already knows what they want.. e.g. `IPAdapter Apply` (yes I know that was changed recently).. and then it ends up returning every single node related to `IPAdapter` and `Apply` (which is less than ideal).

**Comment by getsmartt** [comment]
> They're basically asking for a tokenized search where you split the input string based on whitespace and/or non-"word" characters, perform the search for each token, then merge the results.
> 
> Note: this could be annoying in some cases where a user already knows what they want.. e.g. `IPAdapter Apply` (yes I know that was changed recently).. and then it ends up returning every single node related to `IPAdapter` and `Apply` (which is less than ideal).
> 
> If they truly mean "reverse" because that's the way they're used to speaking (e.g. subject-verb vs verb-subject) then I can't see any non-trivial way that could be done predictably and I wouldn't even try.

True enough, but this could be easily overcome by merging a 'standard' search and a tokenized search and sorting the results with the 'standard'  search first.  Or simply put a checkbox/switch for preference.

**Comment by Nuked88** [comment]
Sooo, I got the fuzzy search working shortly after the first request to improve the search in the Sidebar, I used fuse.js and it worked decently then I found another implementation that seemed to work better so I decided to go with that one, but I stopped because of this reverse thing, it's not there I don't have half an idea how to implement it but I just don't want to make it too slow and imprecise 
And yes, 100% I will make an option in the menu to switch from standard to fuzzy which I will probably enable by default at that point!

**Comment by Nuked88** [comment]
Ok, I've implemented the fuzzy search, which is working even in reverse. You can disable it in the settings if you still want to use the default one!
