### ISSUE TITLE
Strange behavior with the NotePlus node from the MTB Nodes suite

### ISSUE THREAD

**Issue by alessandroperilli** [Nuked88/ComfyUI-N-Sidebar#19]
For some reason, the sidebar insists in placing the `NotePlus` node from the [MTB Nodes](https://github.com/melMass/comfy_mtb) suite (by @melmass), at the top of the list (even if I didn't pin it), but it refuses to show a preview of it:

<img width="1184" alt="Screenshot 2024-03-26 at 21 10 33" src="https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/9775949/9dc81f94-2cbe-4079-a513-104e066967ba">

What you see in the screenshot is me hovering on the `NotePlus` element, and the Sidebar showing the preview of the first available node below. I don't even know why that node appears there.

This behavior happens only in the expanded view. The NotePlus element disappears in the compact view.

Thank you for your help.

**Comment by Nuked88** [comment]
wow that's weird, if you open comfyUI on another browser it's doing the same thing?

**Comment by alessandroperilli** [comment]
Yes on Safari. Vivaldi (Chromium engine) and Safari are the only two browsers I use on macOS.

**Comment by Nuked88** [comment]
weird, i've installed MTB Nodes, but i don't have nothing pinned,can you install [Edit This Cookie](https://chromewebstore.google.com/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?pli=1) on vivaldi and when are in ComfyUI just click on the cookie button and tell me what's the value of the one called "pinnedItems"?

About the preview: it is normal that there is not one, since NotePlus is not a normal node but a javascript node with no input or output, and in these types of nodes it is practically impossible to ganerate a preview, the only way would be to have an image, but maybe I will do something like that later.

**Comment by alessandroperilli** [comment]
There you have it:
<img width="1728" alt="Screenshot 2024-03-27 at 22 16 29" src="https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/9775949/43f0dd18-27ba-4c85-9a59-0b483a12722c">

I don't mind not having a preview of Note+, and in fact, it's probably for the best. 

I'd just like to not have it pinned at the top if I don't want to, and not see the preview of the node underneath.

**Comment by Nuked88** [comment]
Oh, but it's not pinned. The problem is that it appears as the first node in the list when using the expanded view. I think it's related to the fact that it doesn't have a category at all. In fact, you can't find it in the right-click menu in ComfyUI, or at least I wasn't able to. But I will investigate that!

**Comment by alessandroperilli** [comment]
You are right: I cannot find it in any menu either. If this is the "problem", then it's not a problem at all, and it has nothing to do with the Sidebar.  

@melMass: Do you keep the Note+ node outside of any group by design?

**Comment by melMass** [comment]
Nope that's probably an overlook I'll add a category now!

**Comment by melMass** [comment]
@alessandroperilli Should be good! Let me know!
